name: run-unit-tests
on: push
jobs:
  rununittests:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci
        run: npm ci
      - name: run unit tests
        run: npm test